### ISSUE TITLE
Cumbersome proof caused by carrying `[]exists(cr)` along the way

### ISSUE THREAD

**Issue by marshtompsxd** [vmware-research/verifiable-controllers#70]
The goal of our liveness proof is to prove `[]exists(cr) ~> []match(cr)`, where `[]exists(cr)` is our assumption (our spec never guarantees that `[]exists(cr)` is valid).

In many places, we will need `[]exists(cr)` to prove some liveness or safety lemmas, e.g., a request to get a cr leads to a response that contains the cr content, if cr always exists. However, we cannot conjunct `[]exists(cr)` with `next` when applying `init_invariant` or `wf1` because `spec |= []exists(cr)` is not true.

I end up writing variant lemmas that takes an extra assumption temporal predicate. For example, [wf1_variant_assume_temp](https://github.com/vmware-research/verifiable-controllers/blob/at_most_once_delivery/src/temporal_logic/rules.rs#L990) is such a variant of `wf1`.

This causes some trouble when later applying various temporal logic lemmas. For example, if I have proved `spec |= p ~> q` and `spec |= q /\ []asm ~> r`, I cannot directly apply [leads_to_trans](https://github.com/vmware-research/verifiable-controllers/blob/at_most_once_delivery/src/temporal_logic/rules.rs#L1687) to get `spec |= p /\ []asm ~> r`: I either need to write specialized lemma that considers the assumption, or move `[]asm` around. This is still provable, but quite cumbersome.

A potentially more elegant way is to somehow pack `[]exists(cr)` into the `spec` when applying `wf1` or `init_variant` and unpack them back to the right side of `|=` later. But it is unclear to me how to do so.

**Comment by tchajed** [comment]
The following are equivalent:

- `(□p) ~~> q`
- `□◇(p → q)`
- `◇□p → □◇q`

As a result of that last one in particular, rather than proving `spec |= []exists(cr) ~> []match(cr)` you can prove `spec /\ eventually ([]p) |= true ~> q`. That "eventually" in the hypothesis might be awkward. However, I think you can probably instead prove `[]next /\ []fair /\ []p |= true ~> q` (that is, anything always true from the spec can be used, just not initial facts), but I haven't proven that in Coq yet.

**Comment by marshtompsxd** [comment]
So I guess we need a lemma that says
```
pre:
  []next /\ []fair /\ []assumption |= true ~> P
post:
  init /\ []next /\ []fair |= []assumption ~> P
```

**Comment by marshtompsxd** [comment]
I proved it here: https://github.com/vmware-research/verifiable-controllers/pull/75

It is a bit awkward that our weak fairness assumptions are not directly written in the form of `[]fair` (tho they are still always):
```
    .and(tla_forall(|input| kubernetes_api_next().weak_fairness(input)))
    .and(tla_forall(|input| controller_next(reconciler).weak_fairness(input)))
```

**Comment by marshtompsxd** [comment]
Proved a variant lemma. This should not be a problem.
