### ISSUE TITLE
Proof strategy for `true ~> []match(cr)`

### ISSUE THREAD

**Issue by marshtompsxd** [vmware-research/verifiable-controllers#77]
#75 introduces a lemma that allows us to pack the assumption (`[]exists(cr)`) to the spec and unpack it later. In this way, the goal of our liveness proof becomes `[]next /\ []fair /\ []exists(cr) |= true ~> []match(cr)` (initial fact `init` is not in the spec now).

To prove `true ~> []match(cr)`, we will need to split `true` into different cases and later merge them together. For example, we can prove the following two cases:
1. `!reconcile_running ~> []match(cr)`
2. `reconcile_running ~> []match(cr)`

and merge them to get `true ~> []match(cr)`.

Here, case 1 is an easy path: we will just prove reconcile eventually gets invoked and starts from the initial PC, then eventually moves to the next PC, and so on until the reconcile finishes -- this is basically an execution of the reconcile function.

However, case 2 is tricky here, because when reconcile is running, it might stay at different PCs and we need to prove from each PC it leads to `[]match(cr)`. This requires us to prove some safety invariants such as "if the controller is at PC x, then a request message m1 is in flight or its response message m2 is in flight". Such safety invariants are not hard to come up with but can be super long.

More importantly, sometimes the "safety" invariant depends on the assumption `[]exists(cr)`. For example, we might need to prove "if the controller is at PC x, then a request to get CR is in flight or its response is in flight and the response is OK". This invariant holds only when the CR exists (otherwise the response is Error). In other words, sometimes we need to prove `init /\ []next /\ <>[]exists(cr) |= <>[]inv`. Given our new spec drops the initial fact (`[]next /\ []fair /\ []exists(cr)`), how to prove such an invariant becomes a problem.

**Comment by tchajed** [comment]
If you have `init /\ []next |= [](exists(cr) -> inv)`, then you can get `init /\ []next |= init /\ [](next /\ (exists(cr) -> inv) /\ (exists(cr)' -> inv'))`. Once you apply `unpack_assumptions_from_spec` you'll still have that conditional invariant, but now that you have `[]exists(cr)` you should be able to satisfy the premises for those implications (which seems a bit tedious but should be doable).

Note that there is one thing I dropped to make things simpler - above you're proving `inv` under the instantaneous assumptions `exists(cr)`, but it should also be sound to assume `[]exists(cr)`. I'm not sure if that is needed to prove the invariant in this case.

**Comment by marshtompsxd** [comment]
Thanks @tchajed ! I have one more question. The `inv` I was thinking of is `controller_at_x_pc -> get_cr_req_in_flight \/ ok_resp_in_flight`. We probably cannot prove `[](exists(cr) -> inv)` here: cr exists does not imply the get cr request sent in the past has an ok response (when the request gets processed, the cr might not exist). Thinking twice, what I need to prove is that, if the cr always exists from point t, and the controller sends a get cr request after t, that request has an ok response.

**Comment by marshtompsxd** [comment]
After discussing with @tchajed , we have a proof strategy now. Instead of proving `pc_1 -> get_cr_req_in_flight \/ ok_resp_in_flight`, we should just prove `pc_1 -> get_cr_req_in_flight \/ resp_in_flight` and discuss the two cases for response: if the response is OK, then the controller makes progress towards the next PC; otherwise, the reconcile returns, and thanks to #76 , reconcile will be invoked again from PC 0, and we will prove the execution starting from PC 0 eventually reaches the desired state.

In the liveness proof, we will first prove `pc_0_leads_to_desired_state`, which is a happy path (a series of leads-to) and does not require invariants for any intermediate PC. Then we will prove `pc_1_leads_to_desired_state`, which requires us to first prove the invariant `pc_1 -> get_cr_req_in_flight \/ resp_in_flight`. Then we will reason about three cases:
(1) `pc_1 /\ get_cr_req_in_flight`: We can prove a happy path `pc_1 /\ get_cr_req_in_flight ~> pc_1 /\ ok_resp_in_flight ~> pc_2 /\ ....`.
(2) `pc_2 /\ ok_resp_in_flight`: We can prove an shorter happy path `pc_1 /\ ok_resp_in_flight ~> pc_2 /\ ....`.
(3) `pc_2 /\ err_resp_in_flight`: This is the tricky path. To think of it in reality, it means the cr becomes "always exist" after the controller's request gets processed, so the response is Error. In this case, we will prove `pc_1 /\ err_resp_in_flight ~> no_reconcile ~> pc_0` and then use `pc_0_leads_to_desired_state` to finish the proof.

**Comment by marshtompsxd** [comment]
We have implemented the strategy for simple controller and it works
